apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app4
  namespace: flux-system
spec:
  releaseName: app4
  values:
    image:
      repository: docker.io/mmmarceleza/app4:daee161-20210927010118 # {"$imagepolicy": "flux-system:app4"}
