apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: app4
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: marceleza
  filterTags:
    pattern: "^[a-f0-9]+-(?P<ts>[0-9]*)$"
    extract: '$ts'
  policy:
    numerical:
      order: asc