apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: app2
  namespace: flux-system
spec:  
  interval: 1m
  path: "./clusters/staging/apps/app2"
  sourceRef:
    kind: GitRepository
    name: marceleza
    namespace: flux-system
  prune: true
