apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bmg
  namespace: flux-apps
spec:  
  targetNamespace: bmg
  storageNamespace: bmg
  chart:
    spec:
      chart: helm/bmg
      sourceRef:
        kind: GitRepository
        name: git-bmg
        namespace: flux-apps
  dependsOn: []
  install:
    createNamespace: true
    disableWait: true
    remediation:
      retries: -1
  interval: 1m
  values:
    imagePullSecrets:
      - name: regcred
    replicaCount: 1
