apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app4
  namespace: flux-system
spec:  
  targetNamespace: default
  storageNamespace: default
  chart:
    spec:
      chart: ./clusters/staging/charts/app4
      sourceRef:
        kind: GitRepository
        name: marceleza
        namespace: flux-system
  dependsOn: []
  install:
    createNamespace: true
    disableWait: true
    remediation:
      retries: -1
  interval: 1m
  values:
    imagePullSecrets:
      - name: regcred
    replicaCount: 1

