apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app2
  namespace: flux-system
spec:
  releaseName: app2
  targetNamespace: default
  storageNamespace: default
  chart:
    spec:
      chart: ./clusters/staging/charts/app2
      sourceRef:
        kind: GitRepository
        name: marceleza
        namespace: flux-system
  dependsOn: []
  install:
    createNamespace: true
    disableWait: true
    remediation:
      retries: -1
  interval: 1m
  values:
    replicaCount: 1
    image:
      repository: nginx:alpine
      pullPolicy: IfNotPresent
