apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: flux-system
spec:  
  targetNamespace: app2
  storageNamespace: app2
  chart:
    spec:
      chart: ../podinfo-chart
      sourceRef:
        kind: GitRepository
        name: marceleza
        namespace: flux-system
  dependsOn: []
  install:
    createNamespace: true
    disableWait: true
    remediation:
      retries: -1
  interval: 1m
  values:
    replicaCount: 1
